### ISSUE TITLE
Code des jours

### ISSUE THREAD

**Issue by TrusterBSW** [jbromain/rte-tempo#1]
Bonjour,
Je n'ai aps réussi a trouver la correspondance des code jours avec la tarrification.
Je suppose que 0 est pour indeterminé, 1 pour BLLEU, 2 pour BLANC et 3 pour ROUGE.

Est ce que c'est bien cela ?

**Comment by jbromain** [comment]
Bonjour,

Oui c'est bien ça.
La doc de l'API est ici https://www.api-couleur-tempo.fr/api

Il faut dérouler "JourTempo" en bas dans Shemas pour avoir le détail de chaque valeur.

**Comment by TrusterBSW** [comment]
Ah oui, merci
Je n'avais pas déroulé le codeJour pour avoir la description.

Merci pour le service
