### ISSUE TITLE
Avancer l'heure de disponibilité de la couleur tempo du lendemain

### ISSUE THREAD

**Issue by tomcoch** [jbromain/rte-tempo#10]
Bonjour Romain,

Actuellement on peut récupérer la couleur Tempo du lendemain à partir de 8h10. Cette information étant disponible dès 6h30 sur les serveurs RTE, est il possible d'avancer la mise à jour à 6h40?

Merci.

**Comment by jbromain** [comment]
Bonjour,

J'ai ajouté une interrogation anticipée, effective dès demain.
Par contre, l'heure de mise à dispo officielle est toujours 10h30 pour l'info fiable, et à partir de 8h pour le pré-signalement. Je ne suis pas sûr qu'ils publient aussi tôt tous les jours.

`la seule information de référence relative à la couleur des jours de type Tempo ayant un caractère engageant pour RTE est celle publiée en J-1 à 10h30 sur la présente page. Lorsque les informations à sa disposition le permettent, RTE diffuse un pré-signalement à titre purement informatif entre 8h et 10h30.`
https://www.services-rte.com/fr/visualisez-les-donnees-publiees-par-rte/calendrier-des-offres-de-fourniture-de-type-tempo.html

Jean-Baptiste

**Comment by tomcoch** [comment]
Merci d'avoir ajouté une interrogation anticipée, ça me permet d'avoir l'info avant de partir bosser sans avoir besoin d'aller consulter le site de RTE.
![IMG_20241210_064439](https://github.com/user-attachments/assets/ba76b931-44f3-4718-bac7-72bde93d9e77)
