### ISSUE TITLE
Manque des jours en septembre

### ISSUE THREAD

**Issue by Djibs** [jbromain/rte-tempo#2]
Bonjour,

tout d'abord merci pour cet api, ca simplifie mon travail :-)

Je souhaite récupérer les donnée sur toutes la periode 2023-2024 mais pour septembre ca commence qu'à partir du 12 septembre alors que la période Tempo commence le 1er septembre.

Avec cette requête:

https://www.api-couleur-tempo.fr/api/joursTempo?page=1&periode=2023-2024

Pou éviter de scroller toutes les pages, ce serait bien d'avoir une route pour connaitre les nombre de jours bleu/blanc/rouge restants et qui serait du coup mis à jour tous les jours

Merci

**Comment by jbromain** [comment]
Bonjour,

Les données sont bien là, mais elles ne sont pas dans l'ordre chronologique (l'ordre n'est pas défini).

![image](https://github.com/jbromain/rte-tempo/assets/72972682/bbe86064-58ed-48a5-bd99-150cec53fb06)

Je regarde pour trier dans l'ordre chronologique.
