### ISSUE TITLE
Question: couleur lendemain dispo avant 11h ?

### ISSUE THREAD

**Issue by aymeric106** [jbromain/rte-tempo#5]
Bonjour,
Merci pour le site et le projet.

Je constate régulièrement que le site HelloWatt affiche la couleur du lendemain bien avant 11h (et avant le site EDF ou votre API).
Comment font-ils ?

Merci

**Comment by jbromain** [comment]
Bonjour,

Actuellement la couleur pour demain est déjà indiquée par l'API (bleu, en l'occurence).
Ca dépend des jours... et j'évite d'interroger trop souvent le serveur d'Enedis pour avoir l'info, par crainte que ça ne leur plaise pas et qu'on se fasse bloquer.

Globalement on peut considérer que l'API connait l'info à 10h10 tous les jours, mais elle peut encore changer jusqu'à 11h15 environ.

**Comment by tomcoch** [comment]
Bonjour,

Merci pour votre API.

Je trouve quand même dommage d'attendre 10h10 pour connaître la couleur tempo du lendemain car l'info est diffusée à titre informatif par RTE à partir de 6h30-7h. 

Est ce qu'il serait possible de faire une première interrogation dès 8h?

**Comment by jbromain** [comment]
Bonjour @tomcoch,

En fait, l'heure de mise à dispo de la prévision est très variable selon les jours et périodes de l'année. Quand il n'y a aucun doute (ex: plein été), c'est assez tôt le matin effectivement. Dans les périodes plus indécises, c'est parfois bien plus tard.

Je viens d'ajouter une interrogation à 8h10 et une à 9h10 (j'évite les heures piles, leurs serveurs sont beaucoup sollicités par des tâches automatiques aux heures piles). 

Ce sera effectif dès demain.

**Comment by tomcoch** [comment]
Super merci 👍

L'hiver dernier j'ai suivi les jours tempo sur le site RTE, et j'ai toujours eu l'info quand je me levais vers 7h30, sauf une fois où j'ai l'info qu'à midi. Je pensais que l'API de RTE se mettait à jour au même moment.

Maintenant que j'ai un écran mural avec ESP32 pour le suivi de ma production solaire, je vais rajouter l'affichage des jours tempo grâce à ton API, merci.
