### ISSUE TITLE
codeJour toujours à 0 à 14:00

### ISSUE THREAD

**Issue by hftom** [jbromain/rte-tempo#6]
Hm, hier je paye un café à l'auteur et aujourd'hui ... tomorrow renvoie obstinément "codeJour":0 alors qu'il est 14h19 et que si je lance un curl sur RTE_API_URL le json contient bien :  2024-02-20 : WHITE

**Comment by jbromain** [comment]
Hello,

Fâcheuse coincidence ! 

La tâche cron n'a pas marché ce matin, et comme ma connexion internet personnelle est HS aujourd'hui je n'ai pas eu d'alerte. Désolé pour l'incident, j'ai relancé et c'est ok cette fois.

Pour info, il y a un fallback automatique vers 17h pour ce genre de cas particulier (surcharge du serveur RTE au moment de l'appel); à 17h la charge est moindre, ça fonctionne toujours.

(Merci pour le café !)

**Comment by hftom** [comment]
Oki, merci :)

Bon c'était pas dramatique, au pire j'ai l'info dans la TIC à partir de 20h. Curieux d'ailleurs que ce soit trasmis si tard dans la TIC ... Il y a peut être des services payants à "privilégier" ?

**Comment by jbromain** [comment]
C'est quoi la TIC ?

**Comment by hftom** [comment]
Télé Information Client (https://www.enedis.fr/media/2027/download)
Un port série qui diffuse en permanence peu ou prou les infos défilable sur le compteur.
Exemple "jsonisé" en mode historique :
{
    "ADCO":"021876024934",
    "BBRHCJB":"035695388",
    "BBRHCJR":"000000000",
    "BBRHCJW":"000012840",
    "BBRHPJB":"064059604",
    "BBRHPJR":"000000000",
    "BBRHPJW":"000056010",
    "DEMAIN":"----",
    "HHPHC":"A",
    "IINST1":"013",
    "IINST2":"006",
    "IINST3":"000",
    "IMAX1":"060",
    "IMAX2":"060",
    "IMAX3":"060",
    "ISOUSC":"30",
    "MOTDETAT":"000000",
    "OPTARIF":"BBR(",
    "PAPP":"04870",
    "PMAX":"07110",
    "PPOT":"00",
    "PTEC":"HPJW"
}

**Comment by jbromain** [comment]
Très intéressant. Faut que je me penche là dessus pour la conso instantannée dans la domotique.
